import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateAuthTables1757000000000 implements MigrationInterface {
  name = 'CreateAuthTables1757000000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR NOT NULL UNIQUE,
        login VARCHAR NOT NULL UNIQUE,
        first_name VARCHAR,
        last_name VARCHAR,
        password VARCHAR NOT NULL,
        is_email_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
        email_confirmation_code VARCHAR,
        password_recovery_code VARCHAR,
        confirmation_code_expiration TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at TIMESTAMPTZ
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS device_auth_session (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        ip VARCHAR NOT NULL,
        device_id VARCHAR NOT NULL UNIQUE,
        device_name VARCHAR NOT NULL,
        iat BIGINT NOT NULL,
        exp BIGINT NOT NULL,
        last_active_at BIGINT NOT NULL,
        refresh_token_hash VARCHAR NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at TIMESTAMPTZ
      )
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS device_auth_session');
    await queryRunner.query('DROP TABLE IF EXISTS users');
  }
}
